#       ,------.       ,--------.               ,--.
#       |  .--. ' ,---.'--.  .--',--.--. ,---.  `--' ,--,--.,--,--,
#       |  '--'.'| .-. :  |  |   |  .--'| .-. | ,--.' ,-.  ||      \
#       |  |\  \ \   --.  |  |   |  |   ' '-' ' |  |\ '-'  ||  ||  |
#       `--' '--' `----'  `--'   `--'    `---'.-'  / `--`--'`--''--'
#                                             '---'
#                 https://github.com/retrojan/dots-hypr
#

[main]
font=JetBrainsMono Nerd Font:size=14
prompt=">   "
icon-theme=Papirus-Dark
icons-enabled=yes
lines=15
width=25
horizontal-pad=40
vertical-pad=8
inner-pad=4
match-mode=fzf

[colors]
background=000000ff
text=e0e0e0ff
prompt=ffffffff
input=ffffffff
match=ffb74dff
selection=ffffffff
selection-text=00141Dff
selection-match=ffb74dff
border=ffffffff
counter-color=ffffffff

[border]
width=2
radius=10
selection-radius=5
